### ISSUE TITLE
Borrar ramas antiguas

### ISSUE THREAD

**Issue by drancope** [salahmoustajab/python#3]
Las ramas de este repositorio se crearon originalmente en el mío.

Ya no son necesarias, y en cierta medida, estorban para llevar el trabajo ordenado.

Vas a borrarlas.

El procedimiento es:

- Ir a la pestaña de código (code), y bajo ese menú, apretar el botón de ramas (al lado de "main"). 
- Aparece un nuevo menú horizontal, debajo del primero. En primer lugar vemos las ramas más activas. Podemos verlas todas con el último botón (**All branches**)
- Cada rama tiene una línea, con el botón de papelera, para borrarla.

En lo sucesivo, intentaré crear una nueva rama para proponer modificaciones a través de una *pull request*, lo cual permitirá añadir archivos sin pasar por el proceso de descarga de Moodle y carga en GitHub.

**Comment by salahmoustajab** [comment]
hecho
